### ISSUE TITLE
Sprint 1

### ISSUE THREAD

**Issue by AziziAlmina** [ariftairi/Agile-Software-Development#1]

**Comment by ariftairi** [comment]
- [ Low - Fidelity ]

**Comment by ariftairi** [comment]
- [ Low - Fidelity ]

**Comment by ariftairi** [comment]
- [ Test ] 

- [ TEst ]

**Comment by ariftairi** [comment]
- [ ] 

- [ Test ] @zanasalii

**Comment by ariftairi** [comment]
- [ ] Low - Fidelity

**Comment by ariftairi** [comment]
- [ ] Flowchart @AziziAlmina

**Comment by ariftairi** [comment]
- [ ] Use case diagram @nazanatula

**Comment by ariftairi** [comment]
- [ ] Project Description @nazanatula

**Comment by ariftairi** [comment]
- [ ] Low - Fidelity @ariftairi @zanasalii
