### ISSUE TITLE
Notification ( Front-End )

### ISSUE THREAD

**Issue by ariftairi** [ariftairi/Agile-Software-Development#10]

**Comment by zanasalii** [comment]
![8C845923-9475-44CD-9676-38023387DC6F](https://user-images.githubusercontent.com/59477152/72670990-58c95c80-3a44-11ea-85dd-7e5f6dbd2dad.jpeg)

**Comment by zanasalii** [comment]
![AB287DBA-0670-4078-9FE5-5F8EC076E762](https://user-images.githubusercontent.com/59477152/72670994-667ee200-3a44-11ea-8686-c0d3dc2b0599.jpeg)

**Comment by zanasalii** [comment]
1. Notification Screen 
2. Notification Screen- details
