### ISSUE TITLE
My Profile ( Front-End )

### ISSUE THREAD

**Issue by ariftairi** [ariftairi/Agile-Software-Development#11]

**Comment by zanasalii** [comment]
![FD9C234B-F673-4746-B6A6-BFC6F53D9FE8](https://user-images.githubusercontent.com/59477152/72671020-aa71e700-3a44-11ea-8c59-588cdba6eeaa.jpeg)

**Comment by zanasalii** [comment]
My Profile screen shows personal information of the user , given when Signed Up.
