### ISSUE TITLE
Low - Fidelity

### ISSUE THREAD

**Issue by ariftairi** [ariftairi/Agile-Software-Development#2]

**Comment by zanasalii** [comment]
![4ceb331c-109a-4083-bd92-473d63db267d](https://user-images.githubusercontent.com/59477152/71768176-17995e80-2f14-11ea-997b-d79c80bb5d13.jpeg)
![a5abe7fc-1835-4a4c-81fd-1378f285c2e4](https://user-images.githubusercontent.com/59477152/71768177-17995e80-2f14-11ea-97b8-9b8895853338.jpeg)
![2f7cb861-5262-4715-84d1-23d131676247](https://user-images.githubusercontent.com/59477152/71768178-1831f500-2f14-11ea-8baf-b2f7d505410b.jpeg)
![125bcc8a-5d25-4e02-84e7-ff26952beed1](https://user-images.githubusercontent.com/59477152/71768179-1831f500-2f14-11ea-9776-dbac1fa15056.jpeg)
![a7839c1b-1a95-4099-a702-09611b9c18b9](https://user-images.githubusercontent.com/59477152/71768180-1831f500-2f14-11ea-9327-b5c5446cd490.jpeg)
![IMG_9947](https://user-images.githubusercontent.com/59477152/71768181-1831f500-2f14-11ea-87f1-ed1f556c6312.jpeg)
![0b5d667c-946a-4cac-9368-046b0b4c7bff](https://user-images.githubusercontent.com/59477152/71768182-1831f500-2f14-11ea-9c11-773565b857e9.jpeg)
![ff5294f5-7c86-435c-9a97-1f0da647a163](https://user-images.githubusercontent.com/59477152/71768183-18ca8b80-2f14-11ea-859b-38825f39bd3c.jpeg)

**Comment by zanasalii** [comment]
This is the low-fidelity prototype of our application "Blood Donation" . Here is presented how every screen will look in the app .
