### ISSUE TITLE
Login  ( Front-End )

### ISSUE THREAD

**Issue by ariftairi** [ariftairi/Agile-Software-Development#5]

**Comment by zanasalii** [comment]
![Login](https://user-images.githubusercontent.com/59477152/72208533-04523a00-34a4-11ea-8c11-acdabec37698.jpg)

**Comment by zanasalii** [comment]
This is the Login screen .If the user already has an account he/she just has to type the username and the password then Login . In case there is not an account for them , they have to Sign Up.
