### ISSUE TITLE
Sing Up ( Front-End )

### ISSUE THREAD

**Issue by ariftairi** [ariftairi/Agile-Software-Development#8]

**Comment by zanasalii** [comment]
![90011092-6BC3-46F7-8FB2-4D53CB5A870D](https://user-images.githubusercontent.com/59477152/72211243-28277700-34c8-11ea-821d-d0586528a495.jpeg)

**Comment by zanasalii** [comment]
![30529AD7-9FDC-40D6-A37B-76BBF692578C](https://user-images.githubusercontent.com/59477152/72211246-32497580-34c8-11ea-9370-431fb0374cfa.jpeg)

**Comment by zanasalii** [comment]
Sign Up screen shows what kind of information is needed from user to create an account in this application . Such as personal data , name ,surname , birthdate and so on . Also is very important for the user to give the information about what kind of blood has .
