### ISSUE TITLE
Report Screen ( Front-End )

### ISSUE THREAD

**Issue by ariftairi** [ariftairi/Agile-Software-Development#9]

**Comment by zanasalii** [comment]
![8F82B524-A224-4FB8-BD14-8C37DECF19E8](https://user-images.githubusercontent.com/59477152/72670979-42230580-3a44-11ea-8584-9d76734c9f04.jpeg)

**Comment by zanasalii** [comment]
The Report screen shows the information needed if blood is required . So blood type , Hospital name and location .
